version: '3.8'

services:
  python_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_consumer
    environment:
      DB_USER: mqtt
      DB_PASSWORD: mqtt
      DB_HOST: emqx.xyz.com
      DB_PORT: '5432'
      DB_NAME: mqtt
      MQTT_USERNAME: test
      MQTT_PASSWORD: test
      MQTT_HOST: emqx.xyz.com
      MQTT_PORT: '1883'
# require double $$ to espcape $ in env file
      MQTT_TOPIC: '$$share/connectors/vaow/kabira/#'
      DB_TABLE: TEST_MQTT
      DBC_FILE: /app/main.dbc
    restart: unless-stopped
    # dbc file location
    volumes:
      - /home/lenovo/learning/vaow-connector/:/app/